version: '3.8'
services:
  app:
    build: .
    container_name: apartment-listing
    restart: always
    ports:
      - '3001:3001'
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongo:27017/apartments

  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
