version: "3.8"

services:
  backend:
    build:
      context: ./apartment-listing
    container_name: apartment-listing
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/apartment-listing
    env_file:
      - ./apartment-listing/.env
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./apartment-client
    container_name: apartment-client
    ports:
      - "3000:3000"
    env_file:
      - ./apartment-client/.env
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
